CREATE DATABASE ELECTION_DB;


USE ELECTION_DB;
SHOW TABLES;

CREATE TABLE ADMIN (
    STATUS_ INT DEFAULT 0,
    AADHAR VARCHAR(12) PRIMARY KEY,
    NAME_ VARCHAR(50),
    DOB DATE,
    CITY VARCHAR(50),
    STATE_ VARCHAR(50),
    WALLETADDRESS VARCHAR(50) UNIQUE,
    PHONE VARCHAR(10),
    MAIL VARCHAR(50)
);

USE ELECTION_DB;
CREATE TABLE MODERATOR (
    AADHAR VARCHAR(12) PRIMARY KEY,
    STATUS INT DEFAULT 0,
    VERIFIED_BY VARCHAR(12),
    NAME VARCHAR(50),
    DOB DATE,
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    WALLETADDRESS VARCHAR(50) UNIQUE,
    PHONE VARCHAR(10),
    MAIL VARCHAR(50),
    FOREIGN KEY (VERIFIED_BY) REFERENCES ADMIN(AADHAR)
);

USE ELECTION_DB;
CREATE TABLE VOTER (
    AADHAR VARCHAR(12) PRIMARY KEY,
    STATUS INT DEFAULT 0,
    VERIFIED_BY VARCHAR(12),
    NAME VARCHAR(50),
    DOB DATE,
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    WALLETADDRESS VARCHAR(50) UNIQUE,
    PHONE VARCHAR(10),
    MAIL VARCHAR(50),
    FOREIGN KEY (VERIFIED_BY) REFERENCES MODERATOR(AADHAR)
);

USE ELECTION_DB;
SELECT * FROM ADMIN;

INSERT INTO ADMIN VALUES (1, '000000000000', 'NULL', '1999-01-01', 'CITY', 'STATE', 'WALLETADDRESS', '1234567890', 'NULL');